#!/bin/bash

if [ "$1" = "off" ]; then
mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.off;
echo "xdebug disabled";
else
mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.off /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
echo "xdebug enabled";
fi

supervisorctl restart php-fpm

test